### ISSUE TITLE
About PR?

### ISSUE THREAD

**Issue by Cong222** [blaueck/tf-triplet-demo#2]
Hi, PR from output, is mean_pair_rate.
What is mean_pair_rate and pair_rate.
I checked the code, and found "pair_rate = N_pair_lefted / (FLAGS.n_class_per_iter * FLAGS.n_img_per_class**2)"
Could you tell me something about those?

**Comment by blaueck** [comment]
Hi, @Cong222 . 

When doing semi-hard mining, every batch will generate n_class_per_iter * n_img_per_class**2 candidate triplets. After dropping the easy ones, we will have N_pair_lefted triplets lefted. So the pair_rate is mean how much triplets we generated will contribute to the loss.  The mean_pair_rate is the mean of pair_rate between batches. 

Because semi-hard mining will drop the easy triplets, loss will not decrease significantly during training. But the pair_rate will decrease smoothly.

**Comment by Cong222** [comment]
Thank you! Totally I am clear now, thanks agian.
